### ISSUE TITLE
[Bug-AGB Tutorial]Cannot recognize input FNF mask format

### ISSUE THREAD

**Issue by QianSong-Cherry** [BioPAL/BioPAL#36]
- Problem: 
When running ```input_file_from_stack_based, configuration_file_updated = stack_based_processing_obj.run( input_path_from_query )```, I got this error:
> ERROR:root:Cannot recognize input FNF mask format: valid formats are EQUI7 (an "EQUI7_*/" folder containing equi7 tiles sub-folders, example: "EQUI7_AF025M/E042N048T3) or TANDEM-X (collection of "TDM_FNF_*/" folders 
ERROR:root:biopal error inside StackBasedProcessingAGB: Cannot recognize input FNF mask format: valid formats are EQUI7 (an "EQUI7_*/" folder containing equi7 tiles sub-folders, example: "EQUI7_AF025M/E042N048T3) or TANDEM-X (collection of "TDM_FNF_*/" folders 
Traceback (most recent call last):
 File "/Users/qiansong/Research/post-doc/biomass/BioPAL-main/biopal/utility/utility_functions.py", line 33, in run
   output = self._run(input_file_xml)
 File "/Users/qiansong/Research/post-doc/biomass/BioPAL-main/biopal/agb/main_AGB.py", line 284, in _run
   fnf_format = check_fnf_folder_format(input_params_obj.stack_based_processing.forest_mask_catalogue_folder)
 File "/Users/qiansong/Research/post-doc/biomass/BioPAL-main/biopal/utility/utility_functions.py", line 373, in check_fnf_folder_format
   raise Exception(error_msg)
Exception: Cannot recognize input FNF mask format: valid formats are EQUI7 (an "EQUI7_*/" folder containing equi7 tiles sub-folders, example: "EQUI7_AF025M/E042N048T3) or TANDEM-X (collection of "TDM_FNF_*/" folders

- What I did
1. Setup Configuration according to guide in https://github.com/BioPAL/BioPAL;
2. copying following configuration file from: ```demo_lope_four/reference_output_agb/BIOMASS_L2_20201008T103221/AGB/ConfigurationFile.xml```
to this path: ```BioPAL/biopal/conf/ConfigurationFile_AGB.xml```;
3. Update the inputs/Input_File.xml: 
<output_folder>/Users/qiansong/Research/post-doc/biomass/BioPAL-main/outputs</output_folder>
<L1C_repository>/Users/qiansong/Research/post-doc/biomass/BioPAL-main/BioPAL_test_dataset/demo_lope_four/dataSet</L1C_repository>
<auxiliary_products_folder>/Users/qiansong/Research/post-doc/biomass/BioPAL-main/BioPAL_test_dataset/demo_lope_four/auxiliary_data_pf</auxiliary_products_folder>
4. Run the notebook according to the guide in http://www.biopal.org/.

- What I tried
Copy the code from notebook to a .py file, and run it in PyCharm. Then at the same line, I got the error ```Missing gdalinfo executable```.
@slumnitz

**Comment by emanuelegiorgi** [comment]
@QianSong-Cherry thank you for your feedback and for trying BioPAL.
 

- About the FNF mask problem:
please, check your input file `<auxiliary_products_folder>` section: 
it should point over the folder containing a "_ForestMask_" subfolder
i.e.  `<auxiliary_products_folder>C:\YourPath\demo_lope_four\auxiliary_data_pf</auxiliary_products_folder>`
The ForestMask subfolder structure available from FTP is as follows (please, do not modify it):
`demo_lope_four\auxiliary_data_pf\ForestMask\EQUI7_AF080M\E042N048T6\fnf_mask_AF080M_E042N048T6.tif`

- About your configuration:
do not use the `ConfigurationFile.xml` from reference output, this is an old interface one (we are going to update it soon, my apologies for the inconvenience)
keep the default one already present in `BioPAL/biopal/conf/Configuration_File.xml` instead.

- About Missing gdalinfo executable:
It is complicated to understand what went wrong here, be sure to have the `biopal environment ` loaded into PyCharm: `biopal environment ` needs to be created and activated as explained in README.md and Notebook Tutorial, before launching the python IDE)

Thank you again for your feedback

**Comment by QianSong-Cherry** [comment]
@emanuelegiorgi Thanks for your reply.
- About the FNF mask problem
The problem isn't the ForestMask subfolder structure. It turns out that in MAC OS, there's always a hidden file in every folder (known as .DS_Store). Thus whenever you run ```os.listdir(folder)```, it outputs one more filename. Then the error happens. Consider fix the bug, or I can create pull-request.

**Comment by emanuelegiorgi** [comment]
@QianSong-Cherry 

Thank you again for the feedback,
we provide official support for Windows and Linux platforms only.
If you want to contribute with a pull request with the bug fix for MAC OS, this would be kindly appreciated.

Thanks
